### ISSUE TITLE
Unknown Exception when encounters Exercise or Quiz

### ISSUE THREAD

**Issue by NotThizTime** [vassim/linuxacademy-dl#1]
This issue happens when the program encounters a Exercise or Quiz during download. For example, course 95 has Exercise at the end of Chapter 2. The program will download video from the first two chapters without any problem and then crash after the last video from chapter 2 is downloaded.

> INFO     Logged Out!
ERROR    Unknown Exception
ERROR    'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 150, in main
    la.download()
  File "/home/user/.local/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/home/user/.local/lib/python2.7/site-packages/linuxacademy_dl/course.py", line 99, in download
    asset.download()
  File "/home/user/.local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 131, in download
    for resource in self._resources:
TypeError: 'NoneType' object is not iterable

**Comment by vassim** [comment]
Thank you for your report :+1: ! I'll fix this crash problem as early as possible and sorry for my late reply, I just came back from my vacation. :)

FYI, I'm not planning to enable the feature for downloading the exercises or quizzes by my next release! I'll be publishing a 'To Do' list soon, please refer that one for more info!
