### ISSUE TITLE
Unicode error while downloading "CompTIA Cloud Essentials Certification"

### ISSUE THREAD

**Issue by arush-sal** [vassim/linuxacademy-dl#10]
```
ERROR    Unknown Exception
ERROR    'ascii' codec can't encode character u'\u2019' in position 165: ordinal not in range(128)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/cli.py", line 151, in main
    la.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/course.py", line 99, in download
    asset.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 134, in download
    resource['save_resource_as']
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/downloader.py", line 71, in __call__
    if self.skip_existing and os.path.exists(final_path):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 165: ordinal not in range(128)
```

**Comment by arush-sal** [comment]
As a matter of fact, this issue can simply be fixed by:
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'

**Comment by vassim** [comment]
Thank you for reporting this issue @arush-sal !
