### ISSUE TITLE
'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by shardulsrivastava** [vassim/linuxacademy-dl#16]
While Downloading the LinuxAcademy video, i faced this issue.
Error :

INFO     Logged Out! 
ERROR    Unknown Exception
ERROR    'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\linuxacademy_dl\cli.py", line 220, in main
    la.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\linux_academy.py", line 155, in download
    self._course.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\course.py", line 99, in download
    asset.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 139, in download
    self.save_to
  File "c:\python27\lib\site-packages\linuxacademy_dl\downloader.py", line 105, in __call__
    self.hls_download(download_info, final_path)
  File "c:\python27\lib\site-packages\linuxacademy_dl\downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "c:\python27\lib\site-packages\linuxacademy_dl\hls_decrypt.py", line 52, in __init__
    int(iv, 16) if type(iv) in (type(u''), type(b'')) else iv
  File "c:\python27\lib\site-packages\linuxacademy_dl\hls_decrypt.py", line 69, in iv_from_int
    for i in range(AES.block_size)[::-1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

Python Version  :Python 2.7.13

**Comment by vassim** [comment]
Hi @shardulsrivastava, can u please run the app with `--debug` switch and post the log here? And which course are you trying to download?
