### ISSUE TITLE
'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by helloguangxue** [vassim/linuxacademy-dl#18]
**I get following errors, hope it will be fixed. Thank you very much.**

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/cli.py", line 220, in main
    la.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/course.py", line 99, in download
    asset.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 139, in download
    self.save_to
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/downloader.py", line 105, in __call__
    self.hls_download(download_info, final_path)
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/hls_decrypt.py", line 52, in __init__
    int(iv, 16) if type(iv) in (type(u''), type(b'')) else iv
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/hls_decrypt.py", line 69, in iv_from_int
    for i in range(AES.block_size)[::-1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

**Comment by vassim** [comment]
Hi @helloguangxue, can u please run the app with --debug switch and post the log here? And which course are you trying to download?

**Comment by helloguangxue** [comment]
**Course (Linux Essentials Certification) Link: https://linuxacademy.com/cp/modules/view/id/38**

**I think the log file has the same content as the output errors, here is the log file content, thank you for your time.**

2017-02-26 23:30:25,004 INFO     Debug log file created at /Users/Guangxue/linuxacademy-dl/log/log_2017-02-26T23:30:25.004641.log
2017-02-26 23:30:25,005 DEBUG    Python: CPython 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
2017-02-26 23:30:25,005 DEBUG    Platform: Darwin-16.4.0-x86_64-i386-64bit [Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64]
2017-02-26 23:30:25,005 DEBUG    OS: OS X - 10.12.3 x86_64
2017-02-26 23:30:25,005 INFO     Logging in ...
2017-02-26 23:30:26,615 INFO     Analyzing ...
2017-02-26 23:30:27,072 INFO     Downloading files ...
2017-02-26 23:30:28,646 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux Essential Certification/21 - Special Directories and Files/1 - Symbolic Links.mp4
2017-02-26 23:30:29,922 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux Essential Certification/21 - Special Directories and Files/2 - System files, Special Files, and Sticky Bits.mp4
2017-02-26 23:30:31,734 INFO     Downloading /Users/Guangxue/Downloads/courses/Linux Academy/Linux Essential Certification/17 - Your Computer on the Network/1 - Internet, Network, Routers.mp4
2017-02-26 23:33:02,639 INFO     Logged Out!
2017-02-26 23:33:02,639 ERROR    Unknown Exception
2017-02-26 23:33:02,639 ERROR    'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/cli.py", line 220, in main
    la.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/course.py", line 99, in download
    asset.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 139, in download
    self.save_to
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/downloader.py", line 105, in __call__
    self.hls_download(download_info, final_path)
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/hls_decrypt.py", line 52, in __init__
    int(iv, 16) if type(iv) in (type(u''), type(b'')) else iv
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/hls_decrypt.py", line 69, in iv_from_int
    for i in range(AES.block_size)[::-1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 0: ordinal not in range(128)

**Comment by vassim** [comment]
@helloguangxue, Thanks for reporting this issue, I'll take care of this one. :+1:

**Comment by Klaudioz** [comment]
I think the problem is due to the logout: 2017-02-26 23:33:02,639 INFO Logged Out!

In my case, I had the same error I tried again and I have the problem but in another file at the end.

**Comment by gosse** [comment]
As a workaround, if you re-run the same command, it usually downloads a few more files before quitting. Done enough times, you can download the entire course.

**Comment by vassim** [comment]
@Klaudioz, Nop, The problem wasn't happening because of that logout. Please take a look at 8e592e63c8edcf6570cac93be745dbfc0fe6357e! :wink:
@gosse. I like that idea! You are a genius!! :smile:
