### ISSUE TITLE
Error 104 - 'Connection reset by peer'

### ISSUE THREAD

**Issue by crisarceramos** [vassim/linuxacademy-dl#19]
Hi Vassim, I'm getting below error while downloading..can u help please thanks!

`INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Downloading *************.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
    yield
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 529, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 568, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 769, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 641, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/linuxacademy_dl/cli.py", line 220, in main
    la.download()
  File "/usr/local/lib/python3.4/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python3.4/dist-packages/linuxacademy_dl/course.py", line 99, in download
    asset.download()
  File "/usr/local/lib/python3.4/dist-packages/linuxacademy_dl/assets.py", line 139, in download
    self.save_to
  File "/usr/local/lib/python3.4/dist-packages/linuxacademy_dl/downloader.py", line 105, in __call__
    self.hls_download(download_info, final_path)
  File "/usr/local/lib/python3.4/dist-packages/linuxacademy_dl/downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "/usr/local/lib/python3.4/dist-packages/linuxacademy_dl/hls_decrypt.py", line 83, in decrypt
    cipher.decrypt(self.chunk_stream.read(1024 * AES.block_size))
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.4/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
`

**Comment by vassim** [comment]
@crisarceramos Thank you for reporting this issue. Please make sure that you have a good Internet connectivity there. These kind of issue mostly happens with poor Internet connectivity. Any way I'll add a `try .. except` block to handle that exception! If you are still facing this issue, please run the application with `--debug` switch and paste the log here!

**Comment by gosse** [comment]
Hello, I am having the same issue. 

with --debug: 

`INFO     Debug log file created at /home/mradmin/linuxacademy-dl/log/log_2017-03-10T13:02:29.638145.log
DEBUG    Python: CPython 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
DEBUG    Platform: Linux-4.4.0-53-generic-x86_64-with-Ubuntu-16.04-xenial [#74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016]
DEBUG    OS: Linux - Ubuntu 16.04 xenial
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Skipping already existing file /opt/wget/Linux Academy/70-532/1 - Welcome/1 - Welcome to the 70-532 Certification Prep Course.mp4
INFO     Skipping already existing file /opt/wget/Linux Academy/70-532/1 - Welcome/2 - Course Objectives  Goals.mp4
INFO     Skipping already existing file /opt/wget/Linux Academy/70-532/1 - Welcome/3 - Certification and Best Practices.mp4
INFO     Skipping already existing file /opt/wget/Linux Academy/70-532/6 - Rewind and Next Steps/1 - Next Steps.mp4
INFO     Skipping already existing file /opt/wget/Linux Academy/70-532/5 - Design and Implement Azure PaaS Solutions and Services/1 - Design Azure App Service Web Apps.mp4
INFO     Skipping already existing file /opt/wget/Linux Academy/70-532/5 - Design and Implement Azure PaaS Solutions and Services/2 - Design Azure App Service API Apps.mp4
INFO     Skipping already existing file /opt/wget/Linux Academy/70-532/5 - Design and Implement Azure PaaS Solutions and Services/3 - Implement Azure Functions.mp4
INFO     Skipping already existing file /opt/wget/Linux Academy/70-532/5 - Design and Implement Azure PaaS Solutions and Services/4 - Implement API Management.mp4
INFO     Downloading /opt/wget/Linux Academy/70-532/5 - Design and Implement Azure PaaS Solutions and Services/5 - Develop Azure App Service Logic Apps.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 135, in download
    self.save_to
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/downloader.py", line 119, in __call__
    self.hls_download(download_info, final_path)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/hls_decrypt.py", line 83, in decrypt
    cipher.decrypt(self.chunk_stream.read(1024 * AES.block_size))
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 397, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 316, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.`

**Comment by vassim** [comment]
Hi Guys. I tried to reproduce this problem, but failed. I think this is happening because of some issues in the server side! If you guys are still facing this problem, please re open this issue! Thank you!
