### ISSUE TITLE
Input strings must be a multiple of 16 in length

### ISSUE THREAD

**Issue by helloguangxue** [vassim/linuxacademy-dl#20]
**I think I found another issue
   Course url: https://linuxacademy.com/cp/modules/view/id/58
   Here is the debug log file:**

2017-03-10 23:08:20,782 INFO     Debug log file created at /Users/Guangxue/linuxacademy-dl/log/log_2017-03-10T23:08:20.782253.log
2017-03-10 23:08:20,782 DEBUG    Python: CPython 3.6.0 (default, Jan  1 2017, 17:29:58) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
2017-03-10 23:08:20,782 DEBUG    Platform: Darwin-16.4.0-x86_64-i386-64bit [Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64]
2017-03-10 23:08:20,783 DEBUG    OS: OS X - 10.12.3 x86_64
2017-03-10 23:08:20,783 INFO     Logging in ...
2017-03-10 23:08:22,473 INFO     Analyzing ...
2017-03-10 23:08:22,973 INFO     Downloading files ...
2017-03-10 23:08:24,359 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/1 - Introduction/1 - Introduction and Syllabus.mp4
2017-03-10 23:08:25,501 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/1 - Introduction/2 - Register for the Exam.mp4
2017-03-10 23:08:26,791 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/2 - Network Adminstration/1 - Configure Network Services to Start Automatically at Boot Sysvinit Method.mp4
2017-03-10 23:08:28,047 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/2 - Network Adminstration/2 - Configure Network Services to Start Automatically at Boot SystemD Method.mp4
2017-03-10 23:08:29,181 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/2 - Network Adminstration/3 - Implement Packet Filtering.mp4
2017-03-10 23:08:30,353 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/2 - Network Adminstration/4 - Monitor Network Performance.mp4
2017-03-10 23:08:31,545 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/2 - Network Adminstration/5 - Produce and Deliver Reports on System Use, Outages and User Requests.mp4
2017-03-10 23:08:32,858 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/2 - Network Adminstration/6 - Route IP Traffic Statically and Dynamically Dynamic Route.mp4
2017-03-10 23:08:34,006 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/2 - Network Adminstration/7 - Route IP Traffic Statically and Dynamically Static Route.mp4
2017-03-10 23:08:35,234 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/1 - Configure Systems to Mount Standard, Encrypted and Network File Systems on Demand Standard Filesystems.mp4
2017-03-10 23:08:36,476 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/2 - Configure Systems to Mount Standard, Encrypted and Network File Systems on Demand Encrypted Filesystems.mp4
2017-03-10 23:08:37,655 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/3 - Configure Systems to Mount Standard, Encrypted and Network File Systems on Demand Network Filesystems.mp4
2017-03-10 23:08:38,838 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/4 - Create, Mount and Unmount Standard Linux File Systems.mp4
2017-03-10 23:08:40,048 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/5 - ProvideConfigure Network Shares via NFS Server Setup.mp4
2017-03-10 23:08:41,221 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/6 - ProvideConfigure Network Shares via NFS Client Setup.mp4
2017-03-10 23:08:42,593 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/7 - Transfer Files Securely Via the Network SCP.mp4
2017-03-10 23:08:43,722 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/8 - Transfer Files Securely Via the Network SFTP.mp4
2017-03-10 23:08:44,936 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/9 - Update Packages from the Network, a Repository or the Local File System RHELCentOS - Apache Setup.mp4
2017-03-10 23:08:46,049 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/10 - Update Packages from the Network, a Repository or the Local File System RHELCentOS - Repo Server.mp4
2017-03-10 23:08:47,145 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/11 - Update Packages from the Network, a Repository or the Local File System RHELCentOS Client Setup.mp4
2017-03-10 23:08:48,495 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/12 - Update Packages from the Network, a Repository or the Local File System DebianUbuntu - ProFTP Setup.mp4
2017-03-10 23:08:49,619 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/13 - Update Packages from the Network, a Repository or the Local File System DebianUbuntu - Repository Server.mp4
2017-03-10 23:08:50,848 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/3 - Network Filesystems and File Services/14 - Update Packages from the Network, a Repository or the Local File System DebianUbuntu - Client Setup.mp4
2017-03-10 23:08:51,939 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/4 - Network Security/1 - Configure Apache Log Files.mp4
2017-03-10 23:08:53,072 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/4 - Network Security/2 - Configure the Firewall with IPTables.mp4
2017-03-10 23:08:54,274 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/4 - Network Security/3 - Configuring SSH-Based Remote Access Using PublicPrivate Key Pairs.mp4
2017-03-10 23:08:55,712 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/4 - Network Security/4 - Install and Configure SSL with Apache Certificates and Keys.mp4
2017-03-10 23:08:56,826 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/4 - Network Security/5 - Install and Configure SSL with Apache Server Configuration.mp4
2017-03-10 23:08:58,167 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/5 - Remote Access/1 - Configure the Firewall with IPTables.mp4
2017-03-10 23:08:59,279 INFO     Skipping already existing file /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/6 - HTTP Services/1 - Configure an HTTP Client to Automatically Use a Proxy Server.mp4
2017-03-10 23:09:00,506 INFO     Downloading /Users/Guangxue/Downloads/courses/Linux Academy/Linux System Admin Learning Paths/''3 Senior Level/'1 Linux Foundation Certified System Engineer/6 - HTTP Services/2 - Install and Configure an Apache Web Server RedHatCentOS.mp4
2017-03-10 23:10:12,768 INFO     Logged Out!
2017-03-10 23:10:12,768 ERROR    Unknown Exception
2017-03-10 23:10:12,768 ERROR    Input strings must be a multiple of 16 in length
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python3.6/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python3.6/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 135, in download
    self.save_to
  File "/usr/local/lib/python3.6/site-packages/linuxacademy_dl/downloader.py", line 119, in __call__
    self.hls_download(download_info, final_path)
  File "/usr/local/lib/python3.6/site-packages/linuxacademy_dl/downloader.py", line 80, in hls_download
    itm.raw, hls_data['key'], iv
  File "/usr/local/lib/python3.6/site-packages/linuxacademy_dl/hls_decrypt.py", line 83, in decrypt
    cipher.decrypt(self.chunk_stream.read(1024 * AES.block_size))
  File "/usr/local/lib/python3.6/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
2017-03-10 23:10:12,770 INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by vassim** [comment]
Hi @helloguangxue, Thanks for reporting this issue. I'll take care of this one!

**Comment by eudesfilho** [comment]
Hey, I got the same "Input strings must be a multiple of 16 in lenght" bug while downloading LPI 202 videos, but after trying for a couple of times it worked.

**Comment by henrymohn** [comment]
@eudesfilho I think It worked because it downloads part of the video it errors on, and then the next time you run the download process it sees the partial file and skips to the next video.  I tried the same thing on the LPIC-1 course and found that a video that should have been 27mins long was only 19secs long.

**Comment by henrymohn** [comment]
Just as a follow up, I'm running against the same LPIC-1 course now and it's downloading just fine, so definitely seems like a server(Linux Academy's CDN more specifically) issue.  I checked the videos that were originally having this issue and they are indeed valid, full length videos.
