### ISSUE TITLE
Logged out!

### ISSUE THREAD

**Issue by mabushey** [vassim/linuxacademy-dl#29]
/media # linuxacademy-dl -u user -p pass https://linuxacademy.com/cp/courses/lesson/course/997/lesson/3/completed/2/module/119

INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Skipping already existing file /media/8 - Highly Available & Fault Tolerant VPC Networking/1 - Auto Scaling and Elastic Load Balancing Essentials.mp4
...
INFO     Skipping already existing file /media/29 - Disaster Recovery/1 - Disaster Recovery.mp4
INFO     Skipping already existing file /media/18 - Redshift/1 - RedShift Essentials.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.
/media #

**Comment by mabushey** [comment]
Adding the --debug flag adds this:
DEBUG    Python: CPython 2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]
DEBUG    Platform: Linux-4.4.0-59-generic-x86_64-with [#80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017]
DEBUG    OS: Unknown

**Comment by vassim** [comment]
Hi @mabushey, Thank you for reporting this issue. I think this issue is beyond the scope of this project. The course you are referring here has some missing videos (Eg: SQS Essentials) and this problem must be happening because of that.

**Comment by shoaibahmedbeg** [comment]
Hi Vassim,

I am facing the issue when I tried to download the videos and here is the error I am getting:

]# linuxacademy-dl -u  xxx -p xxxx  https://linuxacademy.com/cp/modules/view/id/204
INFO     Logging in ...
INFO     Retrieving an authentication token. Please wait...
INFO     Authentication token acquired!
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Skipping already existing file /root/Lambda-Deep-Dive-NEW/1 - Getting Started/1 - Course Introduction.mp4
INFO     Skipping already existing file /root/Lambda-Deep-Dive-NEW/1 - Getting Started/2 - About the Course Author.mp4
INFO     Skipping already existing file /root/Lambda-Deep-Dive-NEW/1 - Getting Started/3 - How to Use The Lambda Cipher.mp4
INFO     Skipping already existing file /root/Lambda-Deep-Dive-NEW/1 - Getting Started/4 - Course Features and Tools.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/linux_academy.py", line 222, in download
    self._course.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[-1]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

Kindly advise how to resolved this issue.
