### ISSUE TITLE
Not able to download the videos - getting below error

### ISSUE THREAD

**Issue by mohammednazib** [vassim/linuxacademy-dl#31]
ERROR    Unknown Exception
ERROR    Input strings must be a multiple of 16 in length
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 145, in download
    self.save_to
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/downloader.py", line 135, in __call__
    self.hls_download(download_info, final_path)
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/downloader.py", line 94, in hls_download
    fp, key, iv
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/hls_decrypt.py", line 100, in decrypt
    chunk = cipher.decrypt(chunk)
  File "/usr/lib64/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length

**Comment by vassim** [comment]
Hi there! Thanks for reporting this issue. Can you please call linuxacademy-dl with the --debug flag and submit its complete output here?

**Comment by gkrepo** [comment]
Getting the same issue:

`2017-04-14 21:19:10,315 DEBUG    Executing FFMPEG Command "ffmpeg -loglevel fatal -i /tmp/tmp4z92v0_3 -y -bsf:a aac_adtstoasc -vcodec copy -c copy -crf 50 -f mp4 /root/devops/2 - Deployment With EC2 and Auto Scaling/9 - ELB Security.mp4"
2017-04-14 21:19:10,858 INFO     Downloaded /root/devops/2 - Deployment With EC2 and Auto Scaling/9 - ELB Security.mp4
2017-04-14 21:19:12,912 INFO     Downloading /root/devops/8 - Data Pipeline with DynamoDB/1 - Hands-On Data Pipeline with DynamoDB.mp4
2017-04-14 21:19:27,094 DEBUG    Fetched chunk_resp #0 (911616/911616)
2017-04-14 21:19:27,539 DEBUG    Fetched chunk_resp #1 (900708/900708)
2017-04-14 21:19:28,974 INFO     Logged Out!
2017-04-14 21:19:28,974 ERROR    Unknown Exception
2017-04-14 21:19:28,974 ERROR    Input strings must be a multiple of 16 in length
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/lib/python3.5/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/lib/python3.5/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/lib/python3.5/site-packages/linuxacademy_dl/assets.py", line 145, in download
    self.save_to
  File "/usr/lib/python3.5/site-packages/linuxacademy_dl/downloader.py", line 135, in __call__
    self.hls_download(download_info, final_path)
  File "/usr/lib/python3.5/site-packages/linuxacademy_dl/downloader.py", line 94, in hls_download
    fp, key, iv
  File "/usr/lib/python3.5/site-packages/linuxacademy_dl/hls_decrypt.py", line 100, in decrypt
    chunk = cipher.decrypt(chunk)
  File "/usr/lib64/python3.5/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
2017-04-14 21:19:28,979 INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

`

**Comment by greenthecolour** [comment]
Hi Vassim,

I pretty much get the same error on my Linux machine and also the download does not begin from the start of the course, it starts somewhere from the middle, see the error for more details. On windows the download begins sequentially and fails in the middle. 

Please find the error from my Linux machine : 

INFO     Debug log file created at /root/linuxacademy-dl/log/log_2017-04-15_10-14-53.log
DEBUG    Python: CPython 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
DEBUG    Platform: Linux-4.8.0-36-generic-x86_64-with-Ubuntu-16.04-xenial [#36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017]
DEBUG    OS: Linux - Ubuntu 16.04 xenial
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Downloading /home/comp/Downloads/9 - Download roles from Ansible Galaxy and use them/1 - Ansible galaxy and how its used.mp4
DEBUG    Fetched chunk_resp #0 (1045856/1045856)
DEBUG    Fetched chunk_resp #1 (1315264/1315264)
DEBUG    Fetched chunk_resp #2 (657632/657632)
DEBUG    Fetched chunk_resp #3 (766100/766100)
DEBUG    Fetched chunk_resp #4 (723056/723056)
DEBUG    Fetched chunk_resp #5 (722304/722304)
DEBUG    Fetched chunk_resp #6 (764608/764608)
DEBUG    Fetched chunk_resp #7 (890180/890180)
DEBUG    Fetched chunk_resp #8 (824944/824944)
DEBUG    Fetched chunk_resp #9 (828892/828892)
DEBUG    Fetched chunk_resp #10 (783020/783020)
DEBUG    Fetched chunk_resp #11 (853152/853152)
DEBUG    Fetched chunk_resp #12 (2375192/2375192)
DEBUG    Fetched chunk_resp #13 (1563984/1563984)
DEBUG    Fetched chunk_resp #14 (1390260/1390260)
DEBUG    Fetched chunk_resp #15 (1257168/1257168)
DEBUG    Fetched chunk_resp #16 (931744/931744)
DEBUG    Fetched chunk_resp #17 (2098096/2098096)
DEBUG    Fetched chunk_resp #18 (1685044/1685044)
DEBUG    Fetched chunk_resp #19 (1976820/1976820)
DEBUG    Fetched chunk_resp #20 (1530320/1530320)
DEBUG    Fetched chunk_resp #21 (1402672/1402672)
DEBUG    Fetched chunk_resp #22 (1502120/1502120)
DEBUG    Fetched chunk_resp #23 (1994880/1994880)
DEBUG    Fetched chunk_resp #24 (1375792/1375792)
DEBUG    Fetched chunk_resp #25 (1239680/1239680)
DEBUG    Fetched chunk_resp #26 (505532/505532)
DEBUG    Fetched chunk_resp #27 (496144/496144)
DEBUG    Fetched chunk_resp #28 (956368/956368)
DEBUG    Fetched chunk_resp #29 (900896/900896)
DEBUG    Fetched chunk_resp #30 (720240/720240)
DEBUG    Fetched chunk_resp #31 (491248/491248)
DEBUG    Fetched chunk_resp #32 (718536/718536)
DEBUG    Fetched chunk_resp #33 (736584/736584)
DEBUG    Fetched chunk_resp #34 (953160/953160)
DEBUG    Fetched chunk_resp #35 (987200/987200)
DEBUG    Fetched chunk_resp #36 (981924/981924)
DEBUG    Fetched chunk_resp #37 (577348/577348)
DEBUG    Fetched chunk_resp #38 (503652/503652)
DEBUG    Fetched chunk_resp #39 (495756/495756)
DEBUG    Fetched chunk_resp #40 (505156/505156)
DEBUG    Fetched chunk_resp #41 (528280/528280)
DEBUG    Fetched chunk_resp #42 (520960/520960)
DEBUG    Fetched chunk_resp #43 (621168/621168)
DEBUG    Fetched chunk_resp #44 (791120/791120)
DEBUG    Fetched chunk_resp #45 (748428/748428)
DEBUG    Fetched chunk_resp #46 (1141536/1141536)
DEBUG    Fetched chunk_resp #47 (1787128/1787128)
DEBUG    Fetched chunk_resp #48 (449884/449884)
DEBUG    Fetched chunk_resp #49 (492192/492192)
DEBUG    Fetched chunk_resp #50 (856544/856544)
DEBUG    Fetched chunk_resp #51 (969892/969892)
DEBUG    Fetched chunk_resp #52 (1038704/1038704)
DEBUG    Fetched chunk_resp #53 (544636/544636)
DEBUG    Fetched chunk_resp #54 (517752/517752)
DEBUG    Fetched chunk_resp #55 (738088/738088)
DEBUG    Fetched chunk_resp #56 (1393840/1393840)
DEBUG    Fetched chunk_resp #57 (536368/536368)
DEBUG    Fetched chunk_resp #58 (538244/538244)
DEBUG    Fetched chunk_resp #59 (502160/502160)
DEBUG    Fetched chunk_resp #60 (510992/510992)
DEBUG    Fetched chunk_resp #61 (510608/510608)
DEBUG    Fetched chunk_resp #62 (541816/541816)
DEBUG    Fetched chunk_resp #63 (529600/529600)
DEBUG    Fetched chunk_resp #64 (542568/542568)
DEBUG    Fetched chunk_resp #65 (555728/555728)
DEBUG    Fetched chunk_resp #66 (696176/696176)
DEBUG    Fetched chunk_resp #67 (1109764/1109764)
DEBUG    Fetched chunk_resp #68 (596528/596528)
DEBUG    Fetched chunk_resp #69 (555540/555540)
DEBUG    Fetched chunk_resp #70 (1722848/1722848)
DEBUG    Fetched chunk_resp #71 (1568484/1568484)
DEBUG    Fetched chunk_resp #72 (756512/756512)
DEBUG    Fetched chunk_resp #73 (1003544/1003544)
DEBUG    Fetched chunk_resp #74 (1644064/1644064)
DEBUG    Fetched chunk_resp #75 (1089272/1089272)
DEBUG    Fetched chunk_resp #76 (462292/462292)
DEBUG    Fetched chunk_resp #77 (331264/331264)
INFO     Downloaded /home/comp/Downloads/9 - Download roles from Ansible Galaxy and use them/1 - Ansible galaxy and how its used.mp4
INFO     Downloading /home/comp/Downloads/9 - Download roles from Ansible Galaxy and use them/2 - Lets use multiple roles.mp4
DEBUG    Fetched chunk_resp #0 (506672/506672)
DEBUG    Fetched chunk_resp #1 (489936/489936)
DEBUG    Fetched chunk_resp #2 (481656/481656)
DEBUG    Fetched chunk_resp #3 (490304/490304)
DEBUG    Fetched chunk_resp #4 (510240/510240)
DEBUG    Fetched chunk_resp #5 (508352/508352)
DEBUG    Fetched chunk_resp #6 (500656/500656)
DEBUG    Fetched chunk_resp #7 (1163156/1163156)
DEBUG    Fetched chunk_resp #8 (888300/888300)
DEBUG    Fetched chunk_resp #9 (968952/968952)
DEBUG    Fetched chunk_resp #10 (1920048/1920048)
DEBUG    Fetched chunk_resp #11 (1950704/1950704)
DEBUG    Fetched chunk_resp #12 (2103908/2103908)
DEBUG    Fetched chunk_resp #13 (1240064/1240064)
DEBUG    Fetched chunk_resp #14 (902400/902400)
DEBUG    Fetched chunk_resp #15 (805580/805580)
DEBUG    Fetched chunk_resp #16 (1043212/1043212)
DEBUG    Fetched chunk_resp #17 (1051484/1051484)
DEBUG    Fetched chunk_resp #18 (1057696/1057696)
DEBUG    Fetched chunk_resp #19 (936432/936432)
DEBUG    Fetched chunk_resp #20 (718160/718160)
DEBUG    Fetched chunk_resp #21 (463808/463808)
DEBUG    Fetched chunk_resp #22 (506112/506112)
DEBUG    Fetched chunk_resp #23 (670784/670784)
DEBUG    Fetched chunk_resp #24 (733576/733576)
DEBUG    Fetched chunk_resp #25 (856544/856544)
DEBUG    Fetched chunk_resp #26 (869312/869312)
DEBUG    Fetched chunk_resp #27 (860476/860476)
DEBUG    Fetched chunk_resp #28 (930788/930788)
DEBUG    Fetched chunk_resp #29 (1315436/1315436)
DEBUG    Fetched chunk_resp #30 (823456/823456)
DEBUG    Fetched chunk_resp #31 (714592/714592)
DEBUG    Fetched chunk_resp #32 (661392/661392)
DEBUG    Fetched chunk_resp #33 (504976/504976)
DEBUG    Fetched chunk_resp #34 (519632/519632)
DEBUG    Fetched chunk_resp #35 (533552/533552)
DEBUG    Fetched chunk_resp #36 (542960/542960)
DEBUG    Fetched chunk_resp #37 (540512/540512)
DEBUG    Fetched chunk_resp #38 (787360/787360)
DEBUG    Fetched chunk_resp #39 (1123864/1123864)
DEBUG    Fetched chunk_resp #40 (819120/819120)
DEBUG    Fetched chunk_resp #41 (1529380/1529380)
DEBUG    Fetched chunk_resp #42 (1780368/1780368)
DEBUG    Fetched chunk_resp #43 (1043212/1043212)
DEBUG    Fetched chunk_resp #44 (1746708/1746708)
DEBUG    Fetched chunk_resp #45 (1357744/1357744)
DEBUG    Fetched chunk_resp #46 (447264/447264)
DEBUG    Fetched chunk_resp #47 (452720/452720)
DEBUG    Fetched chunk_resp #48 (465864/465864)
DEBUG    Fetched chunk_resp #49 (332208/332208)
INFO     Downloaded /home/comp/Downloads/9 - Download roles from Ansible Galaxy and use them/2 - Lets use multiple roles.mp4
INFO     Downloading /home/comp/Downloads/6 - Create and use templates to create customized configuration files/1 - Templates - Part 1.mp4
DEBUG    Fetched chunk_resp #0 (1453240/1453240)
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    Input strings must be a multiple of 16 in length
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 145, in download
    self.save_to
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/downloader.py", line 135, in __call__
    self.hls_download(download_info, final_path)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/downloader.py", line 94, in hls_download
    fp, key, iv
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/hls_decrypt.py", line 100, in decrypt
    chunk = cipher.decrypt(chunk)
  File "/usr/local/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by vassim** [comment]
Hi @greenthecolour, Thank you for posting the detailed report here! I'll fix that!

**Comment by dhavalkpatel** [comment]
Hello,
I'm getting below error
ERROR    Unknown Exception
ERROR    'contents'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/linuxacademy_dl-1.0a4-py3.5.egg/linuxacademy_dl/cli.py", line 205, in main
    la.analyze()
  File "/usr/local/lib/python3.5/site-packages/linuxacademy_dl-1.0a4-py3.5.egg/linuxacademy_dl/linux_academy.py", line 218, in analyze
    self._course.assets()
  File "/usr/local/lib/python3.5/site-packages/linuxacademy_dl-1.0a4-py3.5.egg/linuxacademy_dl/course.py", line 80, in assets
    syllabus = self._parse_syllabus()
  File "/usr/local/lib/python3.5/site-packages/linuxacademy_dl-1.0a4-py3.5.egg/linuxacademy_dl/course.py", line 76, in _parse_syllabus
    sp.feed(self._fetch_syllabus())
  File "/usr/local/lib/python3.5/site-packages/linuxacademy_dl-1.0a4-py3.5.egg/linuxacademy_dl/parsers.py", line 62, in feed
    super(SyllabusParser, self).feed(clean_html(data))
  File "/usr/local/lib/python3.5/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.5/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/local/lib/python3.5/html/parser.py", line 421, in parse_endtag
    self.handle_endtag(elem.lower())
  File "/usr/local/lib/python3.5/site-packages/linuxacademy_dl-1.0a4-py3.5.egg/linuxacademy_dl/parsers.py", line 102, in handle_endtag
    self.__buffer['contents'].append(
KeyError: 'contents'
