### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by JonKensy** [vassim/linuxacademy-dl#34]
Encountering the following error:

user@UbuntuUtility:~$ sudo linuxacademy-dl -u -p  --debug -o /User-Share/Linux_Academy/Microsoft\ Azure/Azure_IoT_for_the_Enterprise/ https://linuxacademy.com/cp/modules/view/id/132
INFO     Debug log file created at /home/jkensy/linuxacademy-dl/log/log_2017-05-03_10-05-06.log
DEBUG    Python: CPython 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
DEBUG    Platform: Linux-4.4.0-71-generic-x86_64-with-Ubuntu-16.04-xenial [#92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017]
DEBUG    OS: Linux - Ubuntu 16.04 xenial
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Skipping already existing file /User-Share/Linux_Academy/Microsoft Azure/Azure_IoT_for_the_Enterprise/2 - Azure IoT Ecosystem/1 - IoT Architecture Overview.mp4
INFO     Skipping already existing file /User-Share/Linux_Academy/Microsoft Azure/Azure_IoT_for_the_Enterprise/2 - Azure IoT Ecosystem/2 - Azure IoT Architecture.mp4
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by deepk777** [comment]
Getting the issue with and without --use-ffmpeg
linuxacademy-dl -u *** -p *** --use-ffmpeg https://linuxacademy.com/cp/modules/view/id/119 --debug

2017-08-10 07:47:05,543 DEBUG    Python: CPython 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
2017-08-10 07:47:05,553 DEBUG    Platform: Windows-10
2017-08-10 07:47:05,556 DEBUG    OS: Windows
2017-08-10 07:47:05,559 INFO     Logging in ...
2017-08-10 07:47:08,362 INFO     Analyzing ...
2017-08-10 07:47:09,045 INFO     Downloading files ...
2017-08-10 07:47:10,601 INFO     Logged Out!
2017-08-10 07:47:10,605 ERROR    Unknown Exception
2017-08-10 07:47:10,608 ERROR    list index out of range
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\linuxacademy_dl\cli.py", line 206, in main
    la.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\linux_academy.py", line 155, in download
    self._course.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\course.py", line 102, in download
    asset.download()
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 140, in download
    self.analyze()
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 133, in get_resources
    return processor()
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 108, in __call__
    return self.process()
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "c:\python27\lib\site-packages\linuxacademy_dl\assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range

**Comment by andrewiassur** [comment]
linuxacademy-dl -u -p --debug -o ~/linux_acadmey/essentials/ https://linuxacademy.com/cp/courses/lesson/course/55/lesson/1/module/10
INFO     Debug log file created at /home/andy/linuxacademy-dl/log/log_2017-08-11_17-31-46.log
DEBUG    Python: CPython 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
DEBUG    Platform: Linux-4.4.0-89-generic-x86_64-with-Ubuntu-16.04-xenial [#112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017]
DEBUG    OS: Linux - Ubuntu 16.04 xenial
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by tjmai** [comment]
Having the same issue. Could you please help? Many thanks!

**Comment by mstickler** [comment]
Easy fix, if you "dare" to replace a file ;-)

https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip

**Comment by jerrygsheldon** [comment]
Thanks mstickler!  you fixed my issue

**Comment by Hellboy7** [comment]
@mstickler 
Same error as above while downloading and can you help me with step by step guide for https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip to fix error.
I tried but failed
