### ISSUE TITLE
Unable to run the application (even with the debig flag)

### ISSUE THREAD

**Issue by ridicule777** [vassim/linuxacademy-dl#36]
Unable to run the application with any of the option. Does not even print the usage. 

==================
Traceback (most recent call last):
  File "/usr/bin/linuxacademy-dl", line 7, in <module>
    from linuxacademy_dl.__main__ import main
  File "/usr/lib/python3.6/site-packages/linuxacademy_dl/__main__.py", line 38, in <module>
    from linuxacademy_dl.cli import CLI
  File "/usr/lib/python3.6/site-packages/linuxacademy_dl/cli.py", line 38, in <module>
    from .linux_academy import LinuxAcademy
  File "/usr/lib/python3.6/site-packages/linuxacademy_dl/linux_academy.py", line 42, in <module>
    from .course import Course
  File "/usr/lib/python3.6/site-packages/linuxacademy_dl/course.py", line 42, in <module>
    from .assets import Asset
  File "/usr/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 38, in <module>
    from .downloader import DownloadEngine
  File "/usr/lib/python3.6/site-packages/linuxacademy_dl/downloader.py", line 41, in <module>
    from .hls_decrypt import HLSDecryptAES128
  File "/usr/lib/python3.6/site-packages/linuxacademy_dl/hls_decrypt.py", line 38, in <module>
    from Crypto.Cipher import AES
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/__init__.py", line 79, in <module>
    from Crypto.Cipher._mode_cbc import _create_cbc_cipher
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 41, in <module>
    from Crypto.Random import get_random_bytes
  File "/usr/lib/python3.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib/python3.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib/python3.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    from . import FortunaGenerator
  File "/usr/lib/python3.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 36, in <module>
    from Crypto.Cipher import AES
  File "/usr/lib/python3.6/site-packages/Crypto/Cipher/AES.py", line 82, in <module>
    from Crypto.Cipher import _create_cipher
ImportError: cannot import name '_create_cipher'
==================

**Comment by ridicule777** [comment]
OS: Manjaro Linux
