### ISSUE TITLE
Download is failing with the list index out of range

### ISSUE THREAD

**Issue by anushj200** [vassim/linuxacademy-dl#38]
Can some one please help to fix this issue,
python3 -m linuxacademy_dl -u ************ -p ********* -o /Users/anudeep/linuxacademy/ https://linuxacademy.com/cp/modules/view/id/74

INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by anushj200** [comment]
Result with debug flag,

python3 -m linuxacademy_dl -u ************ -p ********** -o /Users/anudeep/linuxacademy/ https://linuxacademy.com/cp/modules/view/id/74 --debug
INFO     Debug log file created at /Users/anudeep/linuxacademy-dl/log/log_2017-08-10_09-49-51.log
DEBUG    Python: CPython 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
DEBUG    Platform: Darwin-16.5.0-x86_64-i386-64bit [Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64]
DEBUG    OS: OS X - 10.12.4 x86_64
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by mstickler** [comment]
Easy fix, if you "dare" to replace a file ;-)

https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip
