### ISSUE TITLE
Unable to download though having latest version

### ISSUE THREAD

**Issue by nmunagala81** [vassim/linuxacademy-dl#39]
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by mstickler** [comment]
Easy fix, if you "dare" to replace a file ;-)

https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip
