### ISSUE TITLE
list index of of range

### ISSUE THREAD

**Issue by dusansusic** [vassim/linuxacademy-dl#40]
I am unable to download videos from LA. Here is an output from debug output.

INFO     Debug log file created at /home/dusan/linuxacademy-dl/log/log_2017-08-11_08-50-20.log
DEBUG    Python: CPython 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
DEBUG    Platform: Linux-4.11.0-14-generic-x86_64-with-LinuxMint-18.2-sonya [#20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017]
DEBUG    OS: Linux - LinuxMint 18.2 sonya
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range

**Comment by varmakosuri** [comment]
same issue

**Comment by Ashh007** [comment]
same issue, Please help here

**Comment by massimosil** [comment]
Same

**Comment by Hardik2003** [comment]
Same issue. Not able to download even a single course due to the issue. Did anyone find a solution to this?

**Comment by jerrygsheldon** [comment]
I have the Same Issue - My Distro and Kernel Info if it helps
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phaxt** [comment]
The same problem.

**Comment by deepk777** [comment]
Can we have this issue solved before my account gets expired by end of this month.

**Comment by mstickler** [comment]
Easy fix, if you "dare" to replace a file ;-)

https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip

**Comment by sudheer52** [comment]
Hey Dude, can you elaborate  a bit ? @mstickler . Just exactly which file needed to be replaced ?

**Comment by susanafdez** [comment]
@mstickler. I have updated file /usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py and tried to download again but I get this error

INFO     Debug log file created at /root/linuxacademy-dl/log/log_2017-08-23_15-26-19.log
DEBUG    Python: CPython 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
DEBUG    Platform: Linux-3.10.0-327.10.1.el7.x86_64-x86_64-with-centos-7.2.1511-Core [#1 SMP Tue Feb 16 17:03:50 UTC 2016]
DEBUG    OS: Linux - CentOS Linux 7.2.1511 Core
INFO     Logging in ...
ERROR    Unknown Exception
ERROR    HTTPSConnectionPool(host='linuxacademy.com', port=443): Max retries exceeded with url: /cp/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x197b6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 203, in main
    output_folder, args['use_ffmpeg'], args['video_quality']
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 118, in __enter__
    self.login()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 134, in login
    "password": self.password
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/url_templates.py", line 106, in render_url
    return getattr(session, 'request')(**render(dict(url_template)))
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='linuxacademy.com', port=443): Max retries exceeded with url: /cp/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x197b6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by susanafdez** [comment]
@mstickler File updated with your code and downloading!! Thanks!!

File I have updated is /usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py

**Comment by mstickler** [comment]
@sudheer52 assets.py needs to be replaced. You'll have to find it on your system. On my linux box it's at /usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py.

**Comment by sudheer52** [comment]
@mstickler Thanks , it's working !

**Comment by Hardik2003** [comment]
Works like a charm!! Thanks a lot @mstickler . Much appreciated!!

**Comment by Great-Dragon** [comment]
still doesn't work. I've replaced the file in here

`$ ls -la /usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py
-rw-r--r-- 1 root root 4936 Aug 23 05:22 /usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py`

I'm using Ubuntu 17.04

**Comment by mstickler** [comment]
@Great-Dragon delete the file assests.pyc (same location) and try again.

**Comment by Great-Dragon** [comment]
@mstickler Thanks. It worked. 
But still it doesn't work inside Docker Image.

**Comment by mstickler** [comment]
@Great-Dragon Good to here it works for you now. I'm NOT the maintainer of the code, just a normal user like the rest here. I needed the tool, it didn't work, so I fixed it (for me) and thought I should/could share. I'm not using Docker so I ... ;-)

**Comment by Great-Dragon** [comment]
@mstickler Cool. I and everyone else appreciate your contribute to the community. At first I was confused as I thought Docker is required for the tool to work. But it's NOT. I'm really happy about that.

**Comment by shardulsrivastava** [comment]
Great Thanks @mstickler .Just a note in windows replace it 
C:\Python27\Lib\site-packages\linuxacademy_dl
where C:\Python27 is where Python is installed .

**Comment by tianmarin** [comment]
@mstickler thanks for your help!

For the docker container, I did this:
```
apk add --update openssl
cd /opt/linuxacademy-dl/linuxacademy_dl/
cd /opt/linuxacademy-dl/build/lib/linuxacademy_dl/

wget https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip
mv assets.py assets.py_old
unzip assets.py.zip
python /opt/linuxacademy-dl/setup.py install
```
I know there is two directories, but i really don't know which one did the trick 😝  (feel free to check).

**Comment by bhaskartatineni** [comment]
Hi All,

I'm unable to download the videos. Getting the error like "Username or password not found." Please anyone can help on this issue.
