### ISSUE TITLE
Unable to download videos

### ISSUE THREAD

**Issue by mohsaif** [vassim/linuxacademy-dl#41]
INFO     Debug log file created at /root/linuxacademy-dl/log/log_2017-08-14_22-28-37.log
DEBUG    Python: CPython 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
DEBUG    Platform: Linux-3.10.0-514.6.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core [#1 SMP Wed Jan 18 13:06:36 UTC 2017]
DEBUG    OS: Linux - CentOS Linux 7.3.1611 Core
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by sohel4r** [comment]
Same problem here

**Comment by susanafdez** [comment]
Same problem here

**Comment by mstickler** [comment]
Easy fix, if you "dare" to replace a file ;-)

https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip
