### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by DheerajJoshi** [vassim/linuxacademy-dl#44]
This is what I got as output
INFO     Debug log file created at /root/linuxacademy-dl/log/log_2017-08-24_12-52-04.log
DEBUG    Python: CPython 2.7.13 |Anaconda 4.4.0 (64-bit)| (default, Dec 20 2016, 23:09:15) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
DEBUG    Platform: Linux-4.9.0-kali4-amd64-x86_64-with-debian-kali-rolling [#1 SMP Debian 4.9.30-2kali1 (2017-06-22)]
DEBUG    OS: Linux - debian kali-rolling 
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/root/anaconda2/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by DheerajJoshi** [comment]
fixed it ....replaced the assets.py file .... and it start working .... !!!! :)

**Comment by andreifilip** [comment]
What if I use docker to run. Where should I look?
It's enough to re-build the image?

Thanks a lot

**Comment by tianmarin** [comment]
@andreifilip check this one:
https://github.com/vassim/linuxacademy-dl/issues/40#issuecomment-328240628
I got it working in docker (with the replaced file

**Comment by andreifilip** [comment]
Thanks a lot @tianmarin
