### ISSUE TITLE
Logging out Automatically

### ISSUE THREAD

**Issue by naresh219** [vassim/linuxacademy-dl#46]
Hi Vassim,

I have replaced the assets file as you mentioned in earlier issues however, I am not able to download the videos, as it logging out automatically. please refer the following screen shot.
![screen shot 2017-08-30 at 5 13 21 am](https://user-images.githubusercontent.com/31458440/29849155-953c1466-8d42-11e7-9619-c174fb565eea.png)

**Comment by naresh219** [comment]
HI Vassim,

Issue is resolved as my subscription in expired and will be able to download after resubsciption

**Comment by mstickler** [comment]
Good to hear you solved the issue. Btw I was the one who fixed the assets.py file, in case there are other issues ;-)

**Comment by sharmanaman** [comment]
I m again facing issue

INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by mstickler** [comment]
Seems like the old code (with errors) is active again. The command "return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]" is not part of the fixed code I posted.
