### ISSUE TITLE
object has no attribute 'get_extension_for_class'

### ISSUE THREAD

**Issue by adhioutlined** [vassim/linuxacademy-dl#5]
hi, I've got this error while running on my centos 7, 

this is my installed version
```
/m/d/ostack-la >>> linuxacademy-dl -v                                                                                                            (1) : 18:00:20
linuxacademy-dl 1.0.dev2
/m/d/ostack-la >>>
```

and here is error :

```INFO     Logging in ...
ERROR    Unknown Exception
ERROR    'Extensions' object has no attribute 'get_extension_for_class'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 148, in main
    output_folder, args['use_ffmpeg'], args['video_quality']
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 118, in __enter__
    self.login()
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 134, in login
    "password": self.password
  File "/usr/lib/python2.7/site-packages/linuxacademy_dl/url_templates.py", line 109, in render_url
    return getattr(session, 'request')(**render(dict(url_template)))
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/home/adhi/.local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
```

**Comment by vassim** [comment]
Hi @adhioutlined, thanks for reporting this issue! I think you are using an older version of `cryptography` library there! Please upgrade the library (`pip install --upgrade cryptography`) and try again. If you are seeing any error messages while upgrading the library, please visit [this link](http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package?answertab=active#tab-top) and follow the instructions!
