### ISSUE TITLE
linuxacademy-dl has been crashed. Probably because of OS version.

### ISSUE THREAD

**Issue by bryn1u** [vassim/linuxacademy-dl#50]
Hello guys,

I can download video becouse of bug. I tried even from root but the same :(((

root@proton:~/test # linuxacademy-dl --debug -u xxx -p xx https://linuxacademy.com/cp/modules/view/id/39

INFO     Debug log file created at /root/linuxacademy-dl/log/log_2017-09-10_12-37-00.log
DEBUG    Python: CPython 2.7.13 (default, Aug 18 2017, 16:28:38) [GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)]
DEBUG    Platform: FreeBSD-11.1-STABLE-HBSD-amd64-64bit [FreeBSD 11.1-STABLE-HBSD #0  r313908+1b7c0a3bf9a(hardened/11-stable/master): Thu Sep  7 14:42:58 CEST 2017     root@HardenedBSD:/usr/obj/usr/src/sys/Proton]
DEBUG    OS: Unknown
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.
root@proton:~/test # 
Is there any way to fix it ?

**Comment by gesundes** [comment]
Same for me.

**Comment by nemoback** [comment]
Found solution. Thanks to mstickler

Easy fix, if you "dare" to replace a file ;-)https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip
--
location where to replace the file:
/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/

**Comment by mikonoid** [comment]
@nemoback thanks a lot! works for me

**Comment by philroche** [comment]
@nemoback works for me too.
