### ISSUE TITLE
stop working

### ISSUE THREAD

**Issue by nemoback** [vassim/linuxacademy-dl#51]
NFO     Debug log file created at /Users/nemoback/linuxacademy-dl/log/log_2017-09-14_17-17-15.log
DEBUG    Python: CPython 2.7.13 (default, Jul 18 2017, 09:16:53) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
DEBUG    Platform: Darwin-15.6.0-x86_64-i386-64bit [Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64]
DEBUG    OS: OS X - 10.11.6 x86_64
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by kenstuddy** [comment]
I am able to replicate this issue on Ubuntu 16.04 LTS using both Python 2.7 and Python 3.5.

**Comment by mikonoid** [comment]
Mac OS Sierra. I've got same problem 

```
NFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/site-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.
```

**Comment by nemoback** [comment]
Found solution. Thanks to mstickler

Easy fix, if you "dare" to replace a file ;-)https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip
--
location where to replace the file:
/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/
