### ISSUE TITLE
ERROR    list index out of range

### ISSUE THREAD

**Issue by saurabhsharma** [vassim/linuxacademy-dl#55]
DEBUG    Python: CPython 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
DEBUG    Platform: Darwin-17.0.0-x86_64-i386-64bit [Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64]
DEBUG    OS: OS X - 10.13 x86_64
INFO     Logging in ...
INFO     Analyzing ...
INFO     Downloading files ...
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by akopitsa** [comment]
The same issue

**Comment by dkbhadeshiya** [comment]
Getting the same issue.

**Comment by rumeshbandara** [comment]
Same issue here folks. Do we have a workaround for this?

**Comment by akopitsa** [comment]
https://github.com/vassim/linuxacademy-dl/files/1245333/assets.py.zip
Now it works
Just change assets.py

**Comment by saurabhsharma** [comment]
@akopitsa it works!! Thanks for the fix!!

**Comment by saurabhsharma** [comment]
@akopitsa worked for couple of files only. Getting below error after some files downloaded.

```
ERROR    Unknown Exception
ERROR    ('Connection aborted.', error(22, 'Invalid argument'))
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/Library/Python/2.7/site-packages/linuxacademy_dl/assets.py", line 73, in process
    play_list_data = session.get(play_list_url).text
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(22, 'Invalid argument'))
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.
```

**Comment by akopitsa** [comment]
for me it works forever

**Comment by saurabhsharma** [comment]
because of different file formats or file naming conventions?

**Comment by akopitsa** [comment]
video files only

**Comment by saurabhsharma** [comment]
I think I am getting this error because of I am getting logged out frequently. Is there any way I can set logout time?

```
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    ('Connection aborted.', error(22, 'Invalid argument'))
```

**Comment by rumeshbandara** [comment]
@akopitsa Thanks, it worked! 👍

**Comment by pratipghosh** [comment]
Hi,

I am facing same issue with Docker Image for this tool.
As per previous post also replace the assets.py in folowing paths, but stall getting same error.

/opt/linuxacademy-dl/linuxacademy_dl/assets.py
/opt/linuxacademy-dl/build/lib/linuxacademy_dl/assets.py

Can anyone help me to resolve this issue?

Thanks in advance,
Pratip Ghosh

**Comment by naeemkhan12** [comment]
I am getting the same issue i have installed with docker image installation and pip installation but no luck :disappointed: 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 155, in download
    self._course.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 71, in process
    play_list_url = self.get_m3u8_playlist_url(lesson_page_source)
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/assets.py", line 64, in get_m3u8_playlist_url
    return LessonProcessor.m3u8_grabber.findall(lesson_page_source)[0]
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by philroche** [comment]
It looks like linuxacademy have changed their HTML and no longer include the m3u8 URL (JS variable "wowzaUrl2") which linuxacademy-dl is grepping for.

**Comment by HerrFried** [comment]
I am getting this issue with version 1.0a4. News?

**Comment by Great-Dragon** [comment]
Duplicate
https://github.com/vassim/linuxacademy-dl/issues/40
