### ISSUE TITLE
Download exited on exception | local variable 'ts_accumulator' referenced before assignment

### ISSUE THREAD

**Issue by sumit-srivastava** [vassim/linuxacademy-dl#63]
INFO     Logged Out!
ERROR    Unknown Exception
ERROR    local variable 'ts_accumulator' referenced before assignment
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\linuxacademy_dl\cli.py", line 206, in main
    la.download()
  File "build\bdist.win-amd64\egg\linuxacademy_dl\linux_academy.py", line 222, in download
    self._course.download()
  File "build\bdist.win-amd64\egg\linuxacademy_dl\course.py", line 102, in download
    asset.download()
  File "build\bdist.win-amd64\egg\linuxacademy_dl\assets.py", line 145, in download
    self.save_to
  File "build\bdist.win-amd64\egg\linuxacademy_dl\downloader.py", line 135, in __call__
    self.hls_download(download_info, final_path)
  File "build\bdist.win-amd64\egg\linuxacademy_dl\downloader.py", line 107, in hls_download
    ts_accumulator.close()
UnboundLocalError: local variable 'ts_accumulator' referenced before assignment
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure t
o call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by pavleec** [comment]
I confirm the above - the same on https://linuxacademy.com/cp/modules/view/id/50

**Comment by Lauren-Buchholz** [comment]
It is also happening for https://linuxacademy.com/cp/modules/view/id/45
