### ISSUE TITLE
Getting below error after entering username and password

### ISSUE THREAD

**Issue by vilayilarun** [vassim/linuxacademy-dl#65]
2017-12-14 16:52:37,249 INFO     Debug log file created at /root/linuxacademy-dl/log/log_2017-12-14_16-52-37.log
2017-12-14 16:52:37,250 DEBUG    Python: CPython 2.7.13 (default, Dec 22 2016, 09:22:15) [GCC 6.2.1 20160822]
2017-12-14 16:52:37,250 DEBUG    Platform: Linux-3.10.0-693.el7.x86_64-x86_64-with [#1 SMP Tue Aug 22 21:09:27 UTC 2017]
2017-12-14 16:52:37,250 DEBUG    OS: Unknown
2017-12-14 16:52:37,250 ERROR    Unknown Exception
2017-12-14 16:52:37,251 ERROR    invalid literal for int() with base 10: 'course_id'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/cli.py", line 203, in main
    output_folder, args['use_ffmpeg'], args['video_quality']
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/linux_academy.py", line 109, in __init__
    course_id=self.get_course_id(course_url),
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/linux_academy.py", line 125, in get_course_id
    return int(url.rsplit("/", 1)[1])
ValueError: invalid literal for int() with base 10: 'course_id'
2017-12-14 16:52:37,252 INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to ca
ll linuxacademy-dl with the --debug flag and include its complete output.

**Comment by echo-time-cat** [comment]
What was the URL for the course you used when calling linuxacademy-dl? It looks like the course id was not correct/valid.

**Comment by avaika** [comment]
I had the same issue. It turned out that dl script doesn't accept URLs which ends with '/'

Means https://linuxacademy.com/cp/modules/view/id/1/ is incorrect URL, while https://linuxacademy.com/cp/modules/view/id/1 is a correct one.
