### ISSUE TITLE
Getting Trackback issue

### ISSUE THREAD

**Issue by WorkingData** [vassim/linuxacademy-dl#68]
When I go to download videos from linuxacademy it always shows bellow error
Traceback (most recent call last):
  File "/usr/local/bin/linuxacademy-dl", line 7, in <module>
    from linuxacademy_dl.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/__main__.py", line 38, in <module>
    from linuxacademy_dl.cli import CLI
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/cli.py", line 38, in <module>
    from .linux_academy import LinuxAcademy
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/linux_academy.py", line 40, in <module>
    from ._session import session
  File "/usr/local/lib/python2.7/dist-packages/linuxacademy_dl/_session.py", line 38, in <module>
    from requests import sessions
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

I have tried many methods to solve the issue but unable to solve, can anyone please help me.

**Comment by mindovermiles262** [comment]
It looks like it might be an issue with your version of OpenSSL, try `sudo apt-get install openssl` then `pip install pyopenssl`
