### ISSUE TITLE
Not able to login Into Linux Academy 

### ISSUE THREAD

**Issue by AMRUTA-BANDHU-CHAUDHURY** [vassim/linuxacademy-dl#78]
I am able to login into Linux academy from browser, but via linuxacademy-dl command line i am unable to login . My account is not also free account, i have purchased via by paying money, i have passed the username and password also in "" or '' inside this quote also .

C:\Windows\system32>linuxacademy-dl help
Username / Email : "xxxxxx.xxxxxx@gmail.com"
Password:
ERROR    Unknown Exception
ERROR    list index out of range
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\linuxacademy_dl\cli.py", line 203, in main

    output_folder, args['use_ffmpeg'], args['video_quality']
  File "c:\python27\lib\site-packages\linuxacademy_dl\linux_academy.py", line 10
9, in __init__
    course_id=self.get_course_id(course_url),
  File "c:\python27\lib\site-packages\linuxacademy_dl\linux_academy.py", line 12
5, in get_course_id
    return int(url.rsplit("/", 1)[1])
IndexError: list index out of range
INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/i
ssues. Make sure you are using the latest version. Be sure to call linuxacademy-
dl with the --debug flag and include its complete output.

C:\Windows\system32>linuxacademy-dl -u xxxxx.xxxxxxx@gmail.com -p xxxxxxxxxxxxx
 https://linuxacademy.com/cp/courses/lesson/course/1711/lesson/1/module/171 --de
bug
INFO     Debug log file created at C:\Users\Eamrban\linuxacademy-dl\log\log_2018
-06-23_16-06-00.log
DEBUG    Python: CPython 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [M
SC v.1500 64 bit (AMD64)]
DEBUG    Platform: Windows-7-6.1.7601-SP1 [6.1.7601]
DEBUG    OS: Windows - 7 6.1.7601
INFO     Logging in ...
ERROR    Username or email not found! Please try again.

C:\Windows\system32>

**Comment by jcolfej** [comment]
Check #60 pull request ;)

**Comment by ktulinho** [comment]
Does not see to work if you login using google account.
