### ISSUE TITLE
download failed 

### ISSUE THREAD

**Issue by abhik2415** [vassim/linuxacademy-dl#80]
download failed with error below

2018-08-07 16:06:40,374 INFO     Logged Out!
2018-08-07 16:06:40,374 ERROR    Unknown Exception
2018-08-07 16:06:40,375 ERROR    '1080'
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/cli.py", line 206, in main
    la.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/linux_academy.py", line 222, in download
    self._course.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/course.py", line 102, in download
    asset.download()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 140, in download
    self.analyze()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 136, in analyze
    self._resources = self.get_resources()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 133, in get_resources
    return processor()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 108, in __call__
    return self.process()
  File "build/bdist.linux-x86_64/egg/linuxacademy_dl/assets.py", line 79, in process
    parser.parsed_data[self.video_quality]
KeyError: '1080'
2018-08-07 16:06:40,377 INFO     Please report this issue on https://github.com/vassim/linuxacademy-dl/issues. Make sure you are using the latest version. Be sure to call linuxacademy-dl with the --debug flag and include its complete output.

**Comment by taufique786** [comment]
Getting the same error..any fixes?

**Comment by thulasi39** [comment]
Same error. Any fix Pls?
